name: Ejecución Automática Alertas

on:
  schedule:
    # 12:47 UTC = 07:47 AM Hora Colombia (Minuto impar para evitar tráfico en GitHub)
    - cron: '47 12 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    permissions:
      contents: write 

    steps:
      - name: Descargar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          pip install requests beautifulsoup4 pandas spacy holidays urllib3 fastparquet
          python -m spacy download es_core_news_sm

      - name: Ejecutar el Robot
        run: python robot_fiscalia.py

      - name: Guardar el nuevo Excel en GitHub
        run: |
          git config --global user.name "Robot Fiscalia"
          git config --global user.email "bot@ejemplo.com"
          git add Alerta_Fiscalia.xlsx
          # Solo guarda si el archivo realmente cambió
          git diff --quiet && git diff --staged --quiet || (git commit -m "🤖 Actualización automática de alertas" && git push)
