name: Robot Fiscalia Rappi

on:
  schedule:
    - cron: '0 13 * * *' # Se ejecuta a las 8:00 AM hora Colombia
  workflow_dispatch: 

permissions:
  contents: write # 👈 Permite a GitHub guardar el Excel en sí mismo

jobs:
  ejecutar-robot:
    runs-on: ubuntu-latest
    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar librerías
      run: |
        pip install requests beautifulsoup4 pandas spacy pyarrow openpyxl holidays
        python -m spacy download es_core_news_sm

    - name: Ejecutar Robot
      # OJO: Si tu archivo tiene espacios en el nombre, debe ir entre comillas
      run: python "FISCALIA DEFINITIVA.py" 

    - name: Guardar Excel de regreso en GitHub
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add Alerta_Fiscalia.xlsx
        git commit -m "🤖 Actualización diaria de alertas" || echo "No hay cambios para subir"
        git push
